### ISSUE TITLE
Add ability to start several container from same image at once

### ISSUE THREAD

**Issue by PHHENS** [iongion/container-desktop#159]
Dear developer,
Thanks for your work on container-desktop.
Would be nice to allow starting of several container from one same image.
Example : start 8 containers from image debian at same time.
Thanks

**Comment by iongion** [comment]
That looks valid request, for worker / producer / consumer type of workload, I am willing to add it.
But describe a bit your use case with as much details as you can if possible so that I understand the problem better.

Things can get a bit more complicated if for example one wants to launch nginx 10 times as port mappings will need to be handled. What approach should then be taken ? Allow a way to auto allocate ports from a range ? Allow mounts to be configurable too ?

**Comment by PHHENS** [comment]
For my personal need, as default network mode uses a different IP for each container, 
i do ssh on containers, so ports redirection and mounts are not needed.
But the question about port mapping and volume mounts is important. A my point of view, it would be nice to allow port mapping by range (first container maps his port 80 on host port 8080, second container maps his port 80 to host port 8081...).
Thanks

**Comment by iongion** [comment]
![image](https://github.com/user-attachments/assets/b47fb14a-ccb6-45c0-bb3e-d598b368fffa)

Something like this as UI

**Comment by PHHENS** [comment]
Exactly what I meant ;-)

**Comment by iongion** [comment]
![image](https://github.com/user-attachments/assets/d64af0ae-498f-4411-a088-b8a66cc7dd75)

yaay!

**Comment by iongion** [comment]
Done, but I have to release a new version and that will take time, on Windows Store it needs approval.
You can clone the repo and have fun yourself meanwhile.

**Comment by iongion** [comment]
Released in 5.2.3

**Comment by PHHENS** [comment]
Thanks a lot for this great feature, I'll test it next Week.
Have a nice Week End.

**Comment by PHHENS** [comment]
Dear Ionut,
Launch multiple containers with 5.2.4 from one image worked for me.
Would be nice to add ability to start container with attach terminal 
(podman -it)
and to select the related network.

Thanks.

Le ven. 20 sept. 2024 à 21:33:47 +02:00:00, ph ***@***.***> a 
écrit :
> Thanks a lot for this great feature, I'll test it next Week.
> Have a nice Week End.
> 
> Le ven. 20 sept. 2024 à 05:09:36 -07:00:00, Ionut Stoica
