### ISSUE TITLE
Fails to open on macOS (Apple Silicon)

### ISSUE THREAD

**Issue by tubbo** [iongion/container-desktop#162]
I tried to install Container Desktop on an Apple Silicon machine, but I got an alert saying "This application is damaged, you should move it to the trash" when I tried opening it from either the installed `/Applications` directory or the disk image itself.

**Comment by iongion** [comment]
Two things you should be aware

- The mac app is not digitally signed, I can't afford it
- Verify the DMG you downloaded against the checksum that I provided, maybe you have an incomplete download or just re-download and try again

I just checked on my m2 mac

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/e3a0cd61-bd80-428b-8691-0061756dc3dd">

**Comment by iongion** [comment]
There is a guide here on how to run non-digitally signed apps https://github.com/iongion/container-desktop/blob/main/USAGE.md but I don't advise. Better for you would be to just clone the repo and build yourself your own dmg.

**Comment by skull-squadron** [comment]
`xattr -dr com.apple.quarantine /Applications/Container\ Desktop.app`

One problem solved, but it still doesn't do anything even after installing the podman batteries that weren't included.

**Comment by riveryc** [comment]
@iongion would you mind to share what should we do to make it work? 
I'm running into the same issue: 
please check the settings or install the requirements

But I have no where to check the error logs and don't even see any information, and it flashed back to this page. 😂 
I don't know what is required to install...

**Comment by iongion** [comment]
It is in the USAGE.md
Open a terminal and paste

xattr -d com.apple.quarantine /Applications/Container\ Desktop.app

**Comment by iongion** [comment]
I have added tutorial for all major operating systems, I hope you find it useful https://container-desktop.com/#guide-macos
